plugin: gcp_compute
auth_kind: "{{ gcp_auth_kind }}"

# Should be able to use an instance template
- name: create GCP instance
  gcp_compute_instance:
    auth_kind: "{{ gcp_auth_kind }}"
    name: "{{ instance_name }}"
    zone: "{{}}"
    machine_type: "{{}}"
    state: present
    metadata: "{{}}"
    tags:
      items: "{{}}"
    network_interfaces:
    - network:
        self_link: "{{}}"
      subnetwork:
        self_link: "{{}}"
      access_configs: []
    scheduling:
      preemtible: yes
    can_ip_forward: no
    disks:
    - auto_delete: no
      boot: yes
      initialize_params:
        source_image: "{{}}"
    service_accounts:
      - email: "{{}}"
        scopes: "{{}}"
    project: "{{ workspace }}"
  register: dynamic_instance
- name: wait for SSH
  wait_for:
  delay: 120
  host: "{{ build_instance.networkInterfaces[0].networkIP }}"
  port: 22
  state: started
  sleep: 5
- name: add host to dynamic inventory group
  add_host:
    hostname: "{{ dynamic_instance.networkInterfaces[0].networkIP }}"
    groupname: dynamic_instances
  when: private_ip
- name: add host to dynamic inventory group
  add_host:
    hostname: "{{ dynamic_instance.networkInterfaces[0].accessConfigs[0].natIP }}"
    groupname: dynamic_instances
  when: not private_ip
